### ISSUE TITLE
new m1 Mac is not supported

### ISSUE THREAD

**Issue by choeoliv** [xpack-dev-tools/arm-none-eabi-gcc-xpack#12] opened 2020-12-30 06:34 UTC
### Description

Hi I'm using new m1 MacBook Air with Homebrew
It seems there is no darwin-arm64 version on release page.
Is there any plan or beta version for apple silicon?

### Steps to Reproduce

I used command like below.
xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@latest

**Expected behaviour:** install xpack

**Actual behaviour:** error message occurred
error: Platform darwin-arm64 not supported.

### Versions

Big Sur

**Comment by ilg-ul** [comment] 2020-12-30 09:13
Support for the new Macs is planned, but currently I do not have access to such a development machine.

**Comment by choeoliv** [comment] 2020-12-30 11:18
Thank you for your work! I hope it will be soon.

**Comment by ilg-ul** [comment] 2020-12-30 12:33
You're welcome.

I plan to buy a Mac Mini M1, but it is not yet available here, so all I can do is wait for Apple to update their offer.

If you know someone with a Mac Mini or a MacBook Pro that can allow me remote ssh access, I can try to prepare the build environment and run the build scripts, until a permanent solution will be available.

**Comment by yennster** [comment] 2021-03-18 19:10
@ilg-ul Found this thread through googling issues with arm-none-eabi-g++ compiling on an Apple M1 computer, I am actually using https://www.scaleway.com/en/ Scaleway to remote log into an M1 machine that I pay for by the hour, just FYI

**Comment by ilg-ul** [comment] 2021-03-18 19:52
Thank you, Jenny, for the suggestion. I took a quick look at the link, but I'm not sure I understand the details. 

Due to the specifics of the xPack builds, and the lack of a mechanism similar to Docker, I currently need a persistent virtual machine, I cannot use a fresh instance for each build. Is this supported?

**Comment by yennster** [comment] 2021-03-18 22:46
@ilg-ul Hi yes, I spent a few hours using a persistent virtual machine on Scaleway today, it gives you the option to connect via SSH or VNC remote desktop, the remote desktop has a full Mac M1 GUI desktop environment for your use

**Comment by yennster** [comment] 2021-03-18 22:48
(By the way, this isn't a Scaleway ad or anything, I just thought it was useful as I am also needing to debug M1 compile issues haha)

**Comment by ilg-ul** [comment] 2021-03-19 15:34
> I spent a few hours using a persistent virtual machine on Scaleway today

I created an account to experiment with Scaleway, and I noticed that the price is $0.1/hour, with a min 24 hours.

What I did not understand is how much it costs simply to store a dormant virtual machine image. My typical use case is very sporadic, from several minutes from now and then, lets say every month for short binary xPacks, to several hours for toolchains for 4-5 times per year. But preparing the xPack Build Box environment takes many hours, and it is not reasonable to do it before every build.

**Comment by Crazor** [comment] 2021-11-16 10:54
Since this issue was closed a long time ago, I'd like to ask: Did I miss the actual solution? Is this still in the "planned" stage or is there support for arm64 now?

**Comment by ilg-ul** [comment] 2021-11-16 11:23
I got a Mac Mini M1 from MacStadium a few days ago, and I'm working on porting the build scripts to it right now.

There are some problems though, GCC is not yet ported properly to Apple Silicon, there is only a fork of GCC 11.1, which I already built, and there are plans to upstream the changes for GCC 12.0 and probably 11.3, but this will take probably some months to be released.

I'll try to do my best of the existing tools, but I don't know yet how difficult it'll be.

**Comment by Crazor** [comment] 2021-11-16 15:28
I'll gladly help out with testing, I have a Mac Mini and a MacBook Air with Apple Silicon on hand. 
For the time being, I tried to run the Intel version of the toolchain via Rosetta, however I failed to install via XPM, because XPM complains about missing support for arm64, even though I ran it through the `arch` wrapper

**Comment by ilg-ul** [comment] 2021-11-16 15:36
I have no experience with the `arch` wrapper, but, knowing xpm, I don't think it can be tricked. xpm itself is portable, and works well with Apple Silicon, but it has its own logic with architectures, if it does not find the correct entries in `package.json`, it fails.

But if you install the Intel archive in a folder and handle paths manually, does the compiler run under Rosetta?

**Comment by ilg-ul** [comment] 2021-11-16 19:27
The first attempt to build the toolchain failed in GCC with _Undefined symbols for architecture arm64:_ which most probably is caused by GCC 10 not being ready for Apple Silicon.

The first GCC which adds support for Apple Silicon is 11.1. I'll try to take a look at the patches, perhaps some can be back-ported to 10, but I cannot guarantee anything for now. :-(

**Comment by ilg-ul** [comment] 2021-11-17 23:49
After getting [help](https://github.com/iains/gcc-darwin-arm64/issues/49), I managed to build an experimental macOS arm64 toolchain:

- <https://github.com/xpack-dev-tools/pre-releases/releases/tag/experimental>

Please try it, since currently I don't have the development environment to do it myself.

**Comment by ilg-ul** [comment] 2021-11-19 09:55
I just installed the latest Eclipse 2021-12 on a Mini M1, and I could test the toolchain, it seems fine.

@choeoliv, @Crazor, @yennster, could you confirm that the new toolchain works in your environment too?

After manually unpacking the archive, you have to remove the quarantine atribute, otherwise you might not be able to start the binaries (`xattr -dr com.apple.quarantine xpack-*`).

**Comment by Crazor** [comment] 2021-11-22 08:06
That build seems to be working just fine, successfully compiled a bunch of projects and ran them on different boards.

**Comment by ilg-ul** [comment] 2021-11-22 08:21
Thank you! I'm updating all packages; so far only QEMU is problematic.

If everything is fine, I'll release them, probably in about 1 week.

**Comment by kammce** [comment] 2021-12-07 01:02
Were these released?

**Comment by ilg-ul** [comment] 2021-12-07 01:11
If everything goes according to plan, tomorrow should be public.

**Comment by kammce** [comment] 2021-12-07 03:05
Oh whoa! Awesome to hear!

**Comment by ilg-ul** [comment] 2021-12-07 07:40
> I failed to install via XPM, because XPM complains about missing support for arm64, even though I ran it through the arch wrapper

For the records, to get the architecture, `xpm` asks nodeJs, which returns the definition hardcoded at build time, thus the `arch` command does not help in this case.

**Comment by ilg-ul** [comment] 2021-12-07 14:06
Fixed on 2021-12-07.

<https://xpack.github.io/blog/2021/12/07/arm-none-eabi-gcc-v10-3-1-2-3-released/>

**Closed as completed by ilg-ul** 2021-12-07 14:06 UTC

**Comment by hawkinchina** [comment] 2024-11-05 03:34
Can support Macos 10.13.4 ?    the official arm-none-eabi-gcc need 10.15 at least of Macos.

**Comment by ilg-ul** [comment] 2024-11-05 06:54
The x64 binaries are targeted for macOS 10.13, the arm64 binaries for macOS 11.0.
