### ISSUE TITLE
Empty functions in libgcov.a

### ISSUE THREAD

**Issue by Novakov** [xpack-dev-tools/arm-none-eabi-gcc-xpack#1] opened 2019-09-20 07:55 UTC
`libgcov.a` included in 8.3.1 release contains only no-op functions.

Assembly dump of `__gcov_init` function from `lib\gcc\arm-none-eabi\8.3.1\thumb\v7-m\nofp\libgcov.a`:
```
00000000 <__gcov_init>:
   0:	4770      	bx	lr
   2:	bf00      	nop
```

Dump it the same for both Windows and Linux distribution package.

Official release of arm-none-eabi-gcc 8.3.1 from ARM contains full functions.

**Comment by ilg-ul** [comment] 2019-09-20 08:30
I'll investigate, I did not use libgcov before and I have to study a bit to see what went wrong during the build.

**Comment by ilg-ul** [comment] 2019-10-07 21:06
The issues is caused by a configuration error. In the second pass, when the system libraries are built, the `configure` tool checks if the system headers are available, otherwise it concludes it is a special build and defines `-Dinhibit_libc` which generally has the effect of creating empty library functions.

The actual check for the system headers is simple, only the presence of`stdio.h` is verified in the location specified by the `--with-sysroot` option. Usually this points to a full system, and by default the file is expected to be in the `/usr/include` folder. However, in our distribution the headers are in the `/include` folder, and the test fails.

The solution is to also add `--with-native-system-header-dir=/include` to define the correct location. 

A new release will be available soon.

**Comment by ilg-ul** [comment] 2019-10-11 12:42
Fixed in v8.3.1-1.2, on 2019-10-11.

A quick test is to run `arm-none-eabi-nm libgcov.a` and to check if the functions are not empty.

**Comment by ilg-ul** [comment] 2019-10-11 12:43
@Novakov, please check the new release and let me know it the library is also functional, since I do not have a test case for it.

**Comment by Novakov** [comment] 2019-10-14 18:25
@ilg-ul Just checked release 8.3.1-1.2 and code coverage is working nicely. Thanks for the fix!

**Comment by ilg-ul** [comment] 2019-10-14 19:01
You're welcome!

**Closed as completed** 2019-10-14 19:01 UTC
Labels: bug

**Comment by ilg-ul** [comment] 2019-10-14 19:04
Since checking code coverage for embedded systems is not a well known topic, could you contribute a post to the project forum documenting how you did it, so that others can benefit from your experience?

**Comment by Novakov** [comment] 2019-10-16 05:46
Most on this subject is covered here: https://mcuoneclipse.com/2014/12/26/code-coverage-for-embedded-target-with-eclipse-gcc-and-gcov/. Exact implemention depends on how someone is runing unt tests, we are using QEmu with semihosting so it's a lot easier than on hardware.

**Comment by ilg-ul** [comment] 2019-10-16 06:19
you mean you are still using those stubs and manually issuing debugger commands to write the files? they are totally useless, if you create semihosted projects with the f4discovery template, for instance, everything is handled automatically, you don‘t have to do anything but add the compiler and linker options.

**Comment by Novakov** [comment] 2019-10-16 06:22
No, I'm just calling `__gcov_flush` as the last instruction in `main()`. I linked that article because that's what I used when I was getting gcov running the first time and it describes how gcov works.

**Comment by ilg-ul** [comment] 2019-10-16 06:30
Try to simply return from `main()` with an error code as usual, flushing is done automatically at exit.

**Comment by ilg-ul** [comment] 2019-10-16 06:31
Do you have a program named `gcov` in your path?

**Comment by Novakov** [comment] 2019-10-16 06:33
In general case it might work, for me - it doesn't (`exit` in newlib is messing with exit code which is then returned by qemu and I rely on on that exit code).

If you ask if `arm-none-eabi-gcov` is in toolchain, then yes, it is.
I limit number of items in PATH, so even gcc is not there.

**Comment by ilg-ul** [comment] 2019-10-16 06:40
If you are using the semihosting code from the templates and not the librdimon, exit works as expected.

No, I ask about gcov. As far as I know, Eclipse does not know about arm-none-eabi-gcov, so if you can see the nice Eclipse results, I wonder how they are generated.

**Comment by Novakov** [comment] 2019-10-16 06:53
It's been a while since I last used Eclipse IDE, for viewing coverage report I'm using gcovr (it generates HTML reports)

**Comment by ilg-ul** [comment] 2019-10-16 07:17
Another good reason why it would be useful to have your experience in a forum article.
